name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v13
      with:
        java-version: "openjdk@1.17"
    - name: Run tests
      run: sbt test
    - name: Run all examples
      run: sbt runAll
    - name: Check formatting
      run: sbt 'scalafmtSbtCheck; scalafmtCheck'
